#!/usr/bin/env ruby
require_relative 'aoc'

dial = 50
zero_count = 0
AOC.read(1).each_line do
  direction = it[0]
  count = it[1..].to_i

  case direction
  when 'L'
    dial = (dial - count) % 100
  when 'R'
    dial = (dial + count) % 100
  end

  if dial == 0
    zero_count += 1
  end
end

puts zero_count
