#!/usr/bin/env ruby
require_relative 'aoc'

dial = 50
zero_count = 0
AOC.input(day=1).each_line do |line|
  count = line[1..].to_i
  case line[0]
  when 'L'
    dial = (dial - count) % 100
  when 'R'
    dial = (dial + count) % 100
  end
  if dial == 0
    zero_count += 1
  end
end

puts zero_count
