#!/usr/bin/env ruby
require_relative 'aoc'

dial = 50
count = 0
AOC.input(day=1).each_line do |line|
  spins = line[1..].to_i
  case line[0]
  when 'L'
    spins.times do
      dial -= 1
      if dial < 0
        dial = 99
      elsif dial == 0
        count += 1
      end
    end
  when 'R'
    spins.times do
      dial += 1
      if dial > 99
        dial = 0
        count += 1
      end
    end
  end
end

puts count
