#!/usr/bin/env ruby
require_relative 'aoc'

dial = 50
zero_count = 0
AOC.input(day=1).each_line do |line|
  count = line[1..].to_i
  case line[0]
  when 'L'
    count.times do
      dial -= 1
      if dial < 0
        dial = 99
      elsif dial == 0
        zero_count += 1
      end
    end
  when 'R'
    count.times do
      dial += 1
      if dial > 99
        dial = 0
        zero_count += 1
      end
    end
  end
end

puts zero_count
