#!/usr/bin/env ruby
require_relative 'aoc'

invalid_ids = []
AOC.input(day=2).split(',').each do |range|
  ids = range.split('-')
  #(ids[0]..ids[1]).each do |id|
  #  # TODO: Check if ID contain repeating pattern.
  #end
end
puts invalid_ids.reduce(0) { |sum, invalid_id| sum += invalid_id }
