#!/usr/bin/env ruby
require_relative 'aoc'

puts (AOC.input(day=3).each_line.map { |line| line.chomp.chars.map(&:to_i) }.map do |bank|
  bank.combination(2).map { |a, b| "#{a}#{b}".to_i }.max
end.sum)
