#!/usr/bin/env ruby
require_relative 'aoc'

input = AOC.input(day=3)

banks = []
input.each_line do |line|
  bank = []
  line.each_char do |c|
    next if c == "\n"
    bank << c.to_i
  end
  banks << bank
end

largest_joltages = []
banks.each do |bank|
  largest_joltage = "#{bank[0]}#{bank[1]}#{bank[2]}#{bank[3]}#{bank[4]}#{bank[5]}#{bank[6]}#{bank[7]}#{bank[8]}#{bank[9]}#{bank[10]}#{bank[11]}"
  i = 0
  j = 1
  k = 2
  l = 3
  m = 4
  n = 5
  o = 6
  p = 7
  q = 8
  r = 9
  s = 10
  t = 11
  while i < bank.length
    while j < bank.length
      while k < bank.length
        while l < bank.length
          while m < bank.length
            while n < bank.length
              while o < bank.length
                while p < bank.length
                  while q < bank.length
                    while r < bank.length
                      while s < bank.length
                        while t < bank.length
                          joltage = "#{bank[i]}#{bank[j]}#{bank[k]}#{bank[l]}#{bank[m]}#{bank[n]}#{bank[o]}#{bank[p]}#{bank[q]}#{bank[r]}#{bank[s]}#{bank[t]}"
                          largest_joltage = joltage if joltage.to_i > largest_joltage.to_i
                          t += 1
                        end
                        s += 1
                        t = s+1
                      end
                      r += 1
                      s = r+1
                      t = s+1
                    end
                    q += 1
                    r = q+1
                    s = r+1
                    t = s+1
                  end
                  p += 1
                  q = p+1
                  r = q+1
                  s = r+1
                  t = s+1
                end
                o += 1
                p = o+1
                q = p+1
                r = q+1
                s = r+1
                t = s+1
              end
              n += 1
              o = n+1
              p = o+1
              q = p+1
              r = q+1
              s = r+1
              t = s+1
            end
            m += 1
            n = m+1
            o = n+1
            p = o+1
            q = p+1
            r = q+1
            s = r+1
            t = s+1
          end
          l += 1
          m = l+1
          n = m+1
          o = n+1
          p = o+1
          q = p+1
          r = q+1
          s = r+1
          t = s+1
        end
        k += 1
        l = k+1
        m = l+1
        n = m+1
        o = n+1
        p = o+1
        q = p+1
        r = q+1
        s = r+1
        t = s+1
      end
      j += 1
      k = j+1
      l = k+1
      m = l+1
      n = m+1
      o = n+1
      p = o+1
      q = p+1
      r = q+1
      s = r+1
      t = s+1
    end
    i += 1
    j = i+1
    k = j+1
    l = k+1
    m = l+1
    n = m+1
    o = n+1
    p = o+1
    q = p+1
    r = q+1
    s = r+1
    t = s+1
  end
  largest_joltages << largest_joltage.to_i
end
puts largest_joltages.reduce(:+)
